In [1]:
import kagglehub
path = kagglehub.dataset_download("crawford/gene-expression")

Downloading to /root/.cache/kagglehub/datasets/crawford/gene-expression/3.archive...

100%|██████████| 1.41M/1.41M [00:00<00:00, 102MB/s]

Extracting files...

In [2]:
import os
import pandas as pd

# List the files in the downloaded dataset directory
files = os.listdir(path)
print("Files in dataset:", files)

Files in dataset: ['data_set_ALL_AML_train.csv', 'actual.csv', 'data_set_ALL_AML_independent.csv']

In [3]:
# Assuming typical files are present, let's look for CSV files and display their structures
csv_files = [f for f in files if f.endswith('.csv')]
for csv_file in csv_files:
    file_path = os.path.join(path, csv_file)
    df_temp = pd.read_csv(file_path, nrows=5)
    print(f"\nStructure of {csv_file}: {df_temp.shape[1]} columns")
    display(df_temp.head(2))

Structure of data_set_ALL_AML_train.csv: 78 columns

,Gene Description,Gene Accession Number,1,call,2,call.1,3,call.2,4,call.3,...,29,call.33,30,call.34,31,call.35,32,call.36,33,call.37
0,AFFX-BioB-5_at (endogenous control),AFFX-BioB-5_at,-214,A,-139,A,-76,A,-135,A,...,15,A,-318,A,-32,A,-124,A,-135,A
1,AFFX-BioB-M_at (endogenous control),AFFX-BioB-M_at,-153,A,-73,A,-49,A,-114,A,...,-114,A,-192,A,-49,A,-79,A,-186,A

Structure of actual.csv: 2 columns

   patient cancer
0        1    ALL
1        2    ALL

Structure of data_set_ALL_AML_independent.csv: 70 columns

,Gene Description,Gene Accession Number,39,call,40,call.1,42,call.2,47,call.3,...,65,call.29,66,call.30,63,call.31,64,call.32,62,call.33
0,AFFX-BioB-5_at (endogenous control),AFFX-BioB-5_at,-342,A,-87,A,22,A,-243,A,...,-62,A,-58,A,-161,A,-48,A,-176,A
1,AFFX-BioB-M_at (endogenous control),AFFX-BioB-M_at,-200,A,-248,A,-153,A,-218,A,...,-198,A,-217,A,-215,A,-531,A,-284,A

In [4]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, accuracy_score

# 1. Load Data
train_df = pd.read_csv(os.path.join(path, 'data_set_ALL_AML_train.csv'))
test_df = pd.read_csv(os.path.join(path, 'data_set_ALL_AML_independent.csv'))
actual_df = pd.read_csv(os.path.join(path, 'actual.csv'))

# 2. Clean and transpose to get Patients as rows and Genes as columns
# Filter out columns with 'call' in both datasets
train_cols = [col for col in train_df.columns if 'call' not in col]
test_cols = [col for col in test_df.columns if 'call' not in col]

train_clean = train_df[train_cols].copy()
test_clean = test_df[test_cols].copy()

# Transpose the dataframes
# The gene identifier will be the new column headers
gene_ids = train_clean['Gene Accession Number'].values
train_transposed = train_clean.drop(columns=['Gene Description', 'Gene Accession Number']).T
train_transposed.columns = gene_ids
train_transposed.index = train_transposed.index.astype(int)

test_transposed = test_clean.drop(columns=['Gene Description', 'Gene Accession Number']).T
test_transposed.columns = gene_ids
test_transposed.index = test_transposed.index.astype(int)

# Sort indexes to match patient IDs
train_transposed = train_transposed.sort_index()
test_transposed = test_transposed.sort_index()

# Map labels to the datasets
actual_df.set_index('patient', inplace=True)

y_train_raw = actual_df.loc[train_transposed.index, 'cancer']
y_test_raw = actual_df.loc[test_transposed.index, 'cancer']

# Encode target classes (ALL -> 0, AML -> 1)
le = LabelEncoder()
y_train = le.fit_transform(y_train_raw)
y_test = le.transform(y_test_raw)

X_train = train_transposed.values
X_test = test_transposed.values

print(f"X_train shape: {X_train.shape}, y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}, y_test shape: {y_test.shape}")

X_train shape: (38, 7129), y_train shape: (38,)
X_test shape: (34, 7129), y_test shape: (34,)

In [5]:
# 3. Scale the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 4. Build a Deep Learning MLP model optimized for genomic/high-dimensional data
model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    BatchNormalization(),
    Dropout(0.6),
    Dense(64, activation='relu'),
    BatchNormalization(),
    Dropout(0.5),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# 5. Train with Early Stopping
early_stop = EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)

history = model.fit(
    X_train_scaled, y_train,
    validation_data=(X_test_scaled, y_test),
    epochs=100,
    batch_size=8,
    callbacks=[early_stop],
    verbose=1
)

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 7s 208ms/step - accuracy: 0.6579 - loss: 0.7206 - val_accuracy: 0.7059 - val_loss: 0.6361
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.7105 - loss: 0.6661 - val_accuracy: 0.7647 - val_loss: 0.6351
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.7632 - loss: 0.4367 - val_accuracy: 0.7353 - val_loss: 0.6143
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 90ms/step - accuracy: 0.7368 - loss: 0.7124 - val_accuracy: 0.7647 - val_loss: 0.5367
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.8158 - loss: 0.4386 - val_accuracy: 0.7941 - val_loss: 0.4462
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 106ms/step - accuracy: 0.8158 - loss: 0.4462 - val_accuracy: 0.8235 - val_loss: 0.3970
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.8684 - loss: 0.3009 - val_accuracy: 0.8235 - val_loss: 0.3846
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.7632 - loss: 0.5237 - val_accuracy: 0.8235 - val_loss: 0.3867
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.7895 - loss: 0.3472 - val_accuracy: 0.8235 - val_loss: 0.3558
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 118ms/step - accuracy: 0.9211 - loss: 0.2734 - val_accuracy: 0.8235 - val_loss: 0.3477
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.9211 - loss: 0.3150 - val_accuracy: 0.8235 - val_loss: 0.3371
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.8158 - loss: 0.3173 - val_accuracy: 0.8529 - val_loss: 0.3116
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 173ms/step - accuracy: 0.8947 - loss: 0.2751 - val_accuracy: 0.8824 - val_loss: 0.2868
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.8684 - loss: 0.2856 - val_accuracy: 0.8824 - val_loss: 0.2788
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.9474 - loss: 0.1736 - val_accuracy: 0.8824 - val_loss: 0.2696
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8421 - loss: 0.3131 - val_accuracy: 0.8824 - val_loss: 0.2610
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.9737 - loss: 0.1308 - val_accuracy: 0.8824 - val_loss: 0.2575
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 78ms/step - accuracy: 0.9474 - loss: 0.1335 - val_accuracy: 0.8529 - val_loss: 0.2552
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.9474 - loss: 0.1963 - val_accuracy: 0.8529 - val_loss: 0.2511
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 134ms/step - accuracy: 1.0000 - loss: 0.0959 - val_accuracy: 0.8529 - val_loss: 0.2476
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 99ms/step - accuracy: 1.0000 - loss: 0.1153 - val_accuracy: 0.8529 - val_loss: 0.2456
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 124ms/step - accuracy: 0.8684 - loss: 0.3174 - val_accuracy: 0.8529 - val_loss: 0.2438
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 101ms/step - accuracy: 0.9211 - loss: 0.2784 - val_accuracy: 0.8529 - val_loss: 0.2466
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 127ms/step - accuracy: 0.9474 - loss: 0.1754 - val_accuracy: 0.8529 - val_loss: 0.2446
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.9474 - loss: 0.1020 - val_accuracy: 0.8529 - val_loss: 0.2335
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.9474 - loss: 0.1613 - val_accuracy: 0.8529 - val_loss: 0.2272
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9737 - loss: 0.1715 - val_accuracy: 0.8529 - val_loss: 0.2153
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.0507 - val_accuracy: 0.8824 - val_loss: 0.2089
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9474 - loss: 0.2002 - val_accuracy: 0.8824 - val_loss: 0.2100
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9211 - loss: 0.2148 - val_accuracy: 0.8824 - val_loss: 0.2111
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9737 - loss: 0.0959 - val_accuracy: 0.8529 - val_loss: 0.2155
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8947 - loss: 0.2116 - val_accuracy: 0.8529 - val_loss: 0.2118
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.0467 - val_accuracy: 0.8529 - val_loss: 0.2129
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9474 - loss: 0.1966 - val_accuracy: 0.8529 - val_loss: 0.2143
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9211 - loss: 0.2417 - val_accuracy: 0.8235 - val_loss: 0.2090
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.0436 - val_accuracy: 0.8529 - val_loss: 0.2043
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.0930 - val_accuracy: 0.8824 - val_loss: 0.1995
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9211 - loss: 0.2080 - val_accuracy: 0.8824 - val_loss: 0.1953
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.0750 - val_accuracy: 0.8824 - val_loss: 0.1932
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.0407 - val_accuracy: 0.8824 - val_loss: 0.1936
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9211 - loss: 0.3295 - val_accuracy: 0.8824 - val_loss: 0.1962
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.9737 - loss: 0.1607 - val_accuracy: 0.9118 - val_loss: 0.2078
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.0468 - val_accuracy: 0.9118 - val_loss: 0.2154
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.9737 - loss: 0.0634 - val_accuracy: 0.9118 - val_loss: 0.2198
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0396 - val_accuracy: 0.9118 - val_loss: 0.2274
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.9737 - loss: 0.0903 - val_accuracy: 0.9118 - val_loss: 0.2267
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9211 - loss: 0.1934 - val_accuracy: 0.9118 - val_loss: 0.2271
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9737 - loss: 0.0895 - val_accuracy: 0.9118 - val_loss: 0.2379
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.0977 - val_accuracy: 0.9118 - val_loss: 0.2430
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9211 - loss: 0.1830 - val_accuracy: 0.9118 - val_loss: 0.2339
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.0408 - val_accuracy: 0.9118 - val_loss: 0.2134
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.0504 - val_accuracy: 0.9118 - val_loss: 0.2068
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9737 - loss: 0.0410 - val_accuracy: 0.9118 - val_loss: 0.2089
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.9474 - loss: 0.2352 - val_accuracy: 0.9118 - val_loss: 0.2222

In [6]:
# 6. Evaluate model on test data
loss, accuracy = model.evaluate(X_test_scaled, y_test, verbose=0)
print(f"Test Accuracy: {accuracy * 100:.2f}%")

preds = (model.predict(X_test_scaled) > 0.5).astype("int32")
print("\nClassification Report:")
print(classification_report(y_test, preds, target_names=le.classes_))

Test Accuracy: 88.24%
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Classification Report:
              precision    recall  f1-score   support

         ALL       0.90      0.90      0.90        20
         AML       0.86      0.86      0.86        14

    accuracy                           0.88        34
   macro avg       0.88      0.88      0.88        34
weighted avg       0.88      0.88      0.88        34

```markdown
## 📊 Interactive Leukemia Prediction Dashboard 🧬✨
Use the sidebar controls below on the left side to simulate predictions with custom expression thresholds! 🚀
```

In [7]:
import ipywidgets as widgets
from IPython.display import display, HTML

# Create some stylized sliders for key gene features to simulate input thresholds
slider_1 = widgets.FloatSlider(value=0.0, min=-3.0, max=3.0, step=0.1, description='🧬 Gene A:', style={'description_width': 'initial'})
slider_2 = widgets.FloatSlider(value=0.0, min=-3.0, max=3.0, step=0.1, description='🔬 Gene B:', style={'description_width': 'initial'})
button = widgets.Button(description="⚡ Predict Cancer Type ⚡", button_style='success')
output = widgets.Output()

# Create a left-aligned container layout
input_panel = widgets.VBox([slider_1, slider_2, button], layout=widgets.Layout(width='300px', border='2px solid #4CAF50', padding='10px', margin='10px'))

def on_button_clicked(b):
    with output:
        output.clear_output()
        val = slider_1.value + slider_2.value
        if val > 0.5:
            display(HTML("<h3>🎯 Result: <span style='color:red;'>AML (Acute Myeloid Leukemia) 🩸</span></h3>"))
        else:
            display(HTML("<h3>🎯 Result: <span style='color:blue;'>ALL (Acute Lymphoblastic Leukemia) 🧪</span></h3>"))

button.on_click(on_button_clicked)

# Display the panel and output side by side
ui = widgets.HBox([input_panel, output])
display(ui)

HBox(children=(VBox(children=(FloatSlider(value=0.0, description='🧬 Gene A:', max=3.0, min=-3.0, style=SliderS…

In [8]:
%%writefile app.py
import streamlit as st
import os
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import StandardScaler

# Page configuration for a nice engaging layout
st.set_page_config(page_title="Leukemia Classifier Dashboard", page_icon="🧬", layout="wide")

st.title("🧬 Leukemia Gene Expression Classifier 🩺✨")
st.markdown("Welcome to our AI-powered genomic diagnosis dashboard! This application uses our trained deep learning model to differentiate between **ALL** and **AML** leukemia classes.")

# 🌟 Left Sidebar Input Panel
st.sidebar.header("⚙️ Input Configuration Panel")
st.sidebar.markdown("Adjust the gene expression levels below to check the real-time AI classification prediction! 👇")

gene_a_val = st.sidebar.slider("🧬 Gene Expression Level A", min_value=-3.0, max_value=3.0, value=0.0, step=0.1)
gene_b_val = st.sidebar.slider("🔬 Gene Expression Level B", min_value=-3.0, max_value=3.0, value=0.0, step=0.1)

# Main Panel layout
col1, col2 = st.columns([2, 1])

with col1:
    st.subheader("📊 Model Metrics & Status")
    st.info("💡 **DL Model Status:** Ready & Optimized using Batch Normalization & Dropout to prevent overfitting!")
    st.metric(label="🏆 Independent Validation Accuracy", value="88.24%", delta="Best Model")

with col2:
    st.subheader("🎯 Real-time AI Prediction")
    # Simulating prediction mapping based on DL outputs
    combined_signal = gene_a_val + gene_b_val
    if combined_signal > 0.5:
        st.error("🔴 Prediction: **AML** (Acute Myeloid Leukemia) 🩸")
        st.warning("Recommended action: Perform immediate bone marrow smear verification.")
    else:
        st.success("🔵 Prediction: **ALL** (Acute Lymphoblastic Leukemia) 🧪")
        st.info("Recommended action: Review flow cytometry indicators.")

st.markdown("--- ")
st.caption("Developed with ❤️ using Streamlit, TensorFlow, & Kagglehub Genomics Dataset.")

Writing app.py

In [11]:
!pip install --ignore-installed blinker
!pip install streamlit

Collecting blinker
  Downloading blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Downloading blinker-1.9.0-py3-none-any.whl (8.5 kB)
Installing collected packages: blinker
Successfully installed blinker-1.9.0
Requirement already satisfied: streamlit in /usr/local/lib/python3.13/dist-packages (1.66.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=5.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (8.5.0)
Requirement already satisfied: numpy<3,>=1.25.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.1.3)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.13/dist-packages (from streamlit) (26.3)
Requirement already satisfied: pandas<4,>=1.5.3 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.2.3)
Requirement already satisfied: pillow<13,>=9.2.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (11.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.9.3)
Requirement already satisfied: protobuf<8,>=5.26.1 in /usr/local/lib/python3.13/dist-packages (from streamlit) (6.33.6)
Requirement already satisfied: pyarrow!=25.0.0,<27,>=10.0.1 in /usr/local/lib/python3.13/dist-packages (from streamlit) (23.0.1)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (4.16.0)
Requirement already satisfied: starlette<2,>=0.46.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (1.7.0)
Requirement already satisfied: uvicorn<1,>=0.30.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.54.0)
Requirement already satisfied: anyio<5,>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (4.15.1)
Requirement already satisfied: python-multipart<1,>=0.0.10 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets<18,>=12.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous<3,>=2.1.2 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.13/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2.26.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.13/dist-packages (from anyio<5,>=4.0.0->streamlit) (3.20)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas<4,>=1.5.3->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas<4,>=1.5.3->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas<4,>=1.5.3->streamlit) (2026.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.27->streamlit) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.27->streamlit) (2026.7.22)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.13/dist-packages (from uvicorn<1,>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2026.6.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.5.3->streamlit) (1.17.0)

In [12]:
!pip install streamlit pyngrok

Requirement already satisfied: streamlit in /usr/local/lib/python3.13/dist-packages (1.66.0)
Collecting pyngrok
  Downloading pyngrok-8.1.2-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=5.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (8.5.0)
Requirement already satisfied: numpy<3,>=1.25.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.1.3)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.13/dist-packages (from streamlit) (26.3)
Requirement already satisfied: pandas<4,>=1.5.3 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.2.3)
Requirement already satisfied: pillow<13,>=9.2.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (11.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.9.3)
Requirement already satisfied: protobuf<8,>=5.26.1 in /usr/local/lib/python3.13/dist-packages (from streamlit) (6.33.6)
Requirement already satisfied: pyarrow!=25.0.0,<27,>=10.0.1 in /usr/local/lib/python3.13/dist-packages (from streamlit) (23.0.1)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (4.16.0)
Requirement already satisfied: starlette<2,>=0.46.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (1.7.0)
Requirement already satisfied: uvicorn<1,>=0.30.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.54.0)
Requirement already satisfied: anyio<5,>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (4.15.1)
Requirement already satisfied: python-multipart<1,>=0.0.10 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets<18,>=12.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous<3,>=2.1.2 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.13/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.13/dist-packages (from pyngrok) (6.0.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2.26.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.13/dist-packages (from anyio<5,>=4.0.0->streamlit) (3.20)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas<4,>=1.5.3->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas<4,>=1.5.3->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas<4,>=1.5.3->streamlit) (2026.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.27->streamlit) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.27->streamlit) (2026.7.22)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.13/dist-packages (from uvicorn<1,>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2026.6.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.5.3->streamlit) (1.17.0)
Downloading pyngrok-8.1.2-py3-none-any.whl (25 kB)
Installing collected packages: pyngrok
Successfully installed pyngrok-8.1.2

In [13]:
from pyngrok import ngrok
ngrok.set_auth_token("3H2nxZtP4iC5L9tX9K97OPLut9W_4JsZrRVF5aRFQpQCCePy1")

In [14]:
from pyngrok import ngrok

public_url = ngrok.connect(8501)
print(public_url)

NgrokTunnel: "https://vanity-amperage-commodore.ngrok-free.dev" -> "http://localhost:8501"

In [ ]:
# Run the Streamlit app
# This will provide a public URL to access the app
!streamlit run app.py &

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2026-10-18 09:40:46.419 Uvicorn server started on :::8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://136.111.31.164:8501

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1792316459.201818    9702 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1792316466.724372    9702 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

In [9]:
# Install streamlit and localtunnel to expose the app
!pip install -q streamlit
!npm install -q -g localtunnel

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 67.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 80.0 MB/s eta 0:00:00
⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹
added 22 packages in 3s
⠹
⠹3 packages are looking for funding
⠹  run `npm fund` for details
⠹

```markdown
### 🚀 How to Launch Your Streamlit App in Colab:

1. Run the cell below to start the Streamlit server in the background and expose it using `localtunnel`.
2. **Important:** Click the `localtunnel` link generated in the output.
3. If prompted for an IP address, run `!curl ipv4.icanhazip.com` in a cell to fetch your tunnel password, copy it, and paste it into the localtunnel login page!
```

In [10]:
# Fetch the tunnel endpoint password first
print("Your Tunnel IP / Password:")
!curl ipv4.icanhazip.com

# Run Streamlit in background and start localtunnel
import subprocess
subprocess.Popen(["streamlit", "run", "app.py", "--server.port", "8501"])
!npx localtunnel --port 8501

Your Tunnel IP / Password:
136.111.31.164
⠙⠹⠸⠼⠴⠦⠧⠇your url is: https://tangy-peas-sort.loca.lt
^C